<?php

/**
 * @file
 * Miscellaneous hook implementations.
 */
define('HAS_FONDS_INDENTIFIER', 'hasFondIdentifier');
define('HAS_VOLUME_INDENTIFIER', 'hasVolumeIdentifier');
define('HAS_FOLDER_INDENTIFIER', 'hasFolderIdentifier');
define('HAS_FILE_INDENTIFIER', 'hasFileIdentifier');

/**
 * Implements hook_menu().
 */
function agile_fonds_importer_menu() {
  $items = array();
  $items['agile/migrate/csv'] = array(
    'title' => 'Import CSV',
    'description' => 'Imports Fonds metadata',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('agile_import_csv_form'),
    'file' => 'includes/agile_migration.inc',
    'access arguments' => array('access content'),
  );
  $items['agile/migrate/volume'] = array(
    'title' => 'Migrate Volume',
    'description' => 'Migrates entire volume from known fond',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('agile_migrate_volume_form'),
    'file' => 'includes/agile_migration.inc',
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements hook_preprocess_theme().
 */
function agile_fonds_importer_process_islandora_large_image(&$variables) {
  $pid = $variables['islandora_object']->id;
  $object = islandora_object_load($pid);
  $relationships = $object->relationships->get();
  $provenance = array();
  foreach ($relationships AS $relationship) {
    switch ($relationship['predicate']['value']) {
      case HAS_FONDS_INDENTIFIER:
        $fond = t('Fond');
        $provenance[] = "$fond : " . $relationship['object']['value'];
        break;

      case HAS_VOLUME_INDENTIFIER:
        $volume = t('Volume');
        $provenance[] = "$volume : " . $relationship['object']['value'];
        break;

      case HAS_FOLDER_INDENTIFIER:
        $folder = t('Folder');
        $provenance[] = "$folder : " . $relationship['object']['value'];
        break;

      case HAS_FILE_INDENTIFIER:
        $file = t('File');
        $provenance[] = "$file : " . $relationship['object']['value'];
        break;
        break;
    }
  }
  $identifier = implode(" | ", $provenance);

  $variables['islandora_content'] = $identifier . $variables['islandora_content'];
}
